const STRINGS = {
    "recipient_address": "Recipient Address",
    "new_contact": "New contact",
    "manage_contacts": "Manage contacts",
    "export_contacts": "Export contacts",
    "import_contacts": "Import contacts",
    "contact_saved": "Contact saved.",
    "contact_list": "Contact list",
    "new_contact": "New contact:",
    "invalid_format": "Cannot import file, wrong format.",
    "contact_conflict_1": "A contact with the address \"%CONTACT%\", but a different name already exists.",
    "contact_conflict_2": "Do you want to override it?",
    "contact_import_done": "Contact import finished.",
    "add_account_hint": "Click the <i class=\"material-icons\">add</i> icon to add an account",
    "import_24_words": "Import from 24 Words",
    "import_access_file": "Import from Access File",
    "import_ledger": "Import Ledger Account",
    "no_accounts": "No accounts yet.",
    "create_account": "Create New Account",
    "loading_accounts": "Loading accounts...",
    "upgraded_hint": "High security account",
    "ledger_hint": "Ledger account",
    "vesting_hint": "Vesting contract",
    "rename": "Rename",
    "backup_recovery_words": "Backup Recovery Words",
    "upgrade": "Upgrade",
    "check_ledger_address": "Check Address on Ledger",
    "balance": "Balance",
    "available_now": "Available now",
    "send_from_account": "Send from this account",
    "pay_out": "Pay out",
    "address_copied": "Account number copied to clipboard",
    "invalid_address_qr": "No address in QR Code!",
    "ticker": "NIM",
    "external_site_warning": "You are opening an external site. Nimiq and its affiliates are not responsible for content on external web pages.",
    "proceed": "Proceed",
    "back": "Back",
    "tx_message": "Message",
    "tx_from": "From",
    "tx_to": "To",
    "tx_block": "Block",
    "tx_date": "Date",
    "tx_fee": "Fee",
    "tx_confirms": "(%CONFIRMS% confirm(s))",
    "account_has_no_balance": "This account has no balance",
    "same_address_as_sender": "This is the same address as the sender",
    "cannot_validate_offline": "Cannot validate address in offline mode",
    "cannot_validate": "Cannot validate address (not connected). Retrying...",
    "invalid_address": "Invalid address",
    "validating_address_type": "Validating address type, please wait...",
    "cannot_send_to_type": "Cannot send to this account type",
    "cannot_send_negative": "You cannot send a negative amount",
    "cannot_send_funds": "You do not have enough funds",
    "bytes_left": "%BYTES% byte(s) remaining",
    "fee_free": "free",
    "fee_standard": "standard",
    "fee_express": "express",
    "ledger_invalid_tx": "Invalid transaction",
    "ledger_invalid_tx_value": "Invalid transaction value",
    "ledger_invalid_tx_fee": "Invalid transaction fee",
    "ledger_invalid_start_height": "Invalid validity start height",
    "ledger_invalid_send_address": "Sender Address doesn't match this ledger account",
    "ledger_invalid_network": "Invalid network",
    "ledger_confirm_address_title": "Confirm Address",
    "ledger_confirm_address_body": "Confirm that the address on your Ledger matches",
    "ledger_address_mismatch": "Address mismatch",
    "ledger_confirm_title": "Confirm transaction",
    "ledger_confirm_body": "Confirm on your Ledger if you want to send the following transaction:",
    "ledger_confirm_from": "From: ",
    "ledger_confirm_to": "To: ",
    "ledger_confirm_value": "Value: ",
    "ledger_confirm_fee": "Fee: ",
    "ledger_one_call_at_a_time": "Only one call at a time allowed",
    "ledger_cancelled": "Request cancelled",
    "ledger_cancel_needed": "Please cancel the previous request on your ledger",
    "ledger_unsupported": "Ledger not supported by browser or support not enabled",
    "network_status_consensus": "Consensus",
    "network_status_peers": "Connected peers",
    "network_status_height": "Blockchain height",
    "network_status_hashrate": "Global hashrate",
    "tx_request_copy": "Copy your address:",
    "tx_request_or_create_link": "OR create a transaction request link:",
    "tx_request_title": "Transaction Request",
    "tx_request_body": "Someone sent you a link to request a transaction. Please proceed to see further details.",
    "ok": "Ok",
    "cancel": "Cancel",
    "prepared_transaction": "Prepared transaction",
    "new_tx": "New Transaction",
    "send_from": "Send from",
    "send_to": "Send to ",
    "advanced_settings": "Advanced Settings",
    "tx_valid_from": "Valid from",
    "tx_valid_from_hint_1": "Only required for offline transaction creation",
    "tx_valid_from_hint_2": "Setting a wrong valid-from height can invalidate your transaction!",
    "tx_send": "Send",
    "loading_txs": "Loading transactions...",
    "refresh_txs": "Refresh",
    "more_txs": "View more",
    "tx_unconfirmed": "pending...",
    "tx_removed": "Transaction was removed",
    "tx_expired": "Transaction has expired",
    "tx": "Transaction",
    "no_txs": "You have no transactions yet",
    "no_txs_offline_mode": "Transactions are not available in offline mode",
    "cashlink_charge": "Charging cashlink",
    "cashlink_redeem": "Redeeming cashlink",
    "edu_slides_please_read": "Please read through this important information.",
    "edu_slides_skip": "Skip AT YOUR OWN RISK",
    "edu_slide_intro_title": "Important Information",
    "edu_slide_intro_you_can_soon": "Alright, you can soon <span class=\"action-text\"></span>. Before that, we have some important information for you.",
    "intro_slide_intro_action_create": "create a new account for Nimiq Safe",
    "intro_slide_intro_action_import_words": "import an existing account",
    "intro_slide_intro_action_import_file": "import an existing account",
    "intro_slide_intro_action_import_ledger": "import an existing account from your ledger",
    "intro_slide_intro_action_upgrade": "upgrade your account for Nimiq Safe",
    "intro_slide_please_read": "Please take your time to understand this for your own safety. 🙏",
    "intro_slide_funds_may_be_stolen": "Your funds may be stolen if you do not heed these warnings",
    "intro_slide_funds_unrecoverable": "We cannot recover your funds or freeze your account if you visit a phishing site or lose your private key.",
    "intro_slide_next": "Nimiq is not a Bank",
    "not_bank_slide_title": "Nimiq Safe is <strong>not</strong> part of a bank",
    "not_bank_slide_subtitle": "Nimiq Safe is an Interface.",
    "not_bank_slide_list_1": "When you create an account in Nimiq Safe, you are generating a cryptographic set of numbers: your private key (represented by 24 Account Recovery Words) and your public key (represented by the Account Number).",
    "not_bank_slide_list_2": "The handling of your keys happens entirely on your computer, inside your browser.",
    "not_bank_slide_list_3": "We never transmit, receive or store your private key, 24 Recovery Words, Pass Phrase, PIN, Account Access File or other account information.",
    "not_bank_slide_list_4": "You are simply using our interface to <strong>interact directly with the blockchain</strong>.",
    "not_bank_slide_list_5": "If you send your account number (public key) to someone, they can send you NIM.",
    "not_bank_slide_list_6": "If you send your private key, 24 Recovery Words or Account Access File with PIN / Pass Phrase to someone, they now have full control of your account.",
    "not_bank_slide_back": "Introduction",
    "not_bank_slide_next": "What is a Blockchain?",
    "blockchain_slide_title": "Wait, what is a Blockchain?",
    "blockchain_slide_list_1": "The blockchain is like a huge, global, decentralized spreadsheet.",
    "blockchain_slide_list_2": "It keeps track of who sent how many coins to whom, and what the balance of every account is.",
    "blockchain_slide_list_3": "It is stored and maintained by thousands of people (miners) across the globe connected to the blockchain with their computers.",
    "blockchain_slide_list_4": "When you see your balance on safe.nimiq.com or view your transactions on nimiq.watch, you are seeing data on the blockchain, not in our personal systems.",
    "blockchain_slide_list_5": "Again: <strong>Nimiq Safe accounts are not part of a bank.</strong>",
    "blockchain_slide_back": "Not a Bank",
    "blockchain_slide_next": "But... Why?",
    "why_slide_title": "Why are you making me read all this?",
    "why_slide_subtitle": "Because we need you to understand that we cannot...",
    "why_slide_list_we_cant_list_1": "Access your account or send your funds for you.",
    "why_slide_list_we_cant_list_2": "Recover or change your private key or 24 Recovery Words.",
    "why_slide_list_we_cant_list_3": "Recover or reset your Pass Phrase or PIN.",
    "why_slide_list_we_cant_list_4": "Reverse, cancel, or refund transactions.",
    "why_slide_list_we_cant_list_5": "Freeze accounts.",
    "why_slide_you_responsible_for_security": "<strong>You</strong> and <strong>only you</strong> are responsible for your security.",
    "why_slide_warning_list_1": "Be diligent to keep your private key and associated 24 Recovery Words, Account Access File and Pass Phrase safe.",
    "why_slide_warning_list_2": "If you lose your private key (24 Recovery Words), Pass Phrase or PIN, no one can recover it.",
    "why_slide_warning_list_3": "If you enter your private key (24 Recovery Words) on a phishing website, you will have <strong>all your funds taken</strong>.",
    "why_slide_next": "What is a Blockchain?",
    "why_slide_back": "So what's the point?",
    "point_of_nimiq_slide_title": "Why can't Nimiq Safe do those things?",
    "point_of_nimiq_slide_reason_list_1": "Because that is the point of decentralization and the blockchain.",
    "point_of_nimiq_slide_reason_list_2": "You don't have to rely on your bank, government, or anyone else when you want to move your funds.",
    "point_of_nimiq_slide_reason_list_3": "You don't have to rely on the security of an exchange or bank to keep your funds safe.",
    "point_of_nimiq_slide_reason_list_4": "If you don't find these things valuable, ask yourself why you think the blockchain and cryptocurrencies are valuable. 😉",
    "point_of_nimiq_slide_next": "But... Why?",
    "point_of_nimiq_slide_back": "Protect your Funds",
    "phishers_slide_title": "How To Protect Yourself from Phishers",
    "phishers_slide_subtitle": "Phishers send you a message with a link to a website that looks just like the Nimiq Safe, Paypal, or your bank, but is not the real website. They steal your information and then steal your money.",
    "phishers_slide_tip_list_1": "Always validate the URL: https://safe.nimiq.com",
    "phishers_slide_tip_list_2": "The only authorized view that will ever ask you for your Pass Phrase, PIN or 24 Recovery Words is the Nimiq Keyguard at https://keyguard.nimiq.com",
    "phishers_slide_tip_list_3": "Do not trust messages or links sent to you randomly via email, Discord, Slack, Reddit, Twitter, etc. Always navigate directly to a site before you enter information. Do not enter information after clicking a link from a message or email.",
    "phishers_slide_tip_list_4": "Install an AdBlocker and do not click ads on your search engine (e.g. Google).",
    "phishers_slide_back": "What's the point?",
    "phishers_slide_next": "Protect from Scams",
    "scams_slide_title": "How To Protect Yourself from Scams",
    "scams_slide_subtitle": "People will try to get you to give them money in return for nothing.",
    "scams_slide_tip_1": "If it is too good to be true, it probably is.",
    "scams_slide_tip_2": "Research before sending money to someone or some project. Look for information on a variety of websites and forums. Be wary.",
    "scams_slide_tip_3": "Ask questions when you don't understand something or it doesn't seem right.",
    "scams_slide_tip_4": "Don't let fear, FUD (fear, uncertainty and doubt), or FOMO (fear of missing out) win over common sense. If something is very urgent, ask yourself \"why?\". It may be to create FOMO or prevent you from doing research.",
    "scams_slide_back": "Phishers",
    "scams_slide_next": "Protect From Loss",
    "loss_slide_title": "How To Protect Yourself from Loss",
    "loss_slide_subtitle": "If you lose your 24 Recovery Words, Pass Phrase or PIN, they are gone forever. Don't lose them.",
    "loss_slide_tip_1": "Make a backup of your 24 Recovery Words and Pass Phrase. Do NOT just store it on your computer. Print it out or write it down on a piece of paper.",
    "loss_slide_tip_2": "Store one or more copies of this paper in one or more secure and private physical locations. A backup is not useful if it is destroyed by a fire or flood along with your computer.",
    "loss_slide_tip_3": "Do not store your 24 Recovery Words in Dropbox, Google Drive, or other cloud storage. If that account is compromised, your funds will be stolen.",
    "loss_slide_next": "Scams",
    "loss_slide_back": "Got it",
    "outro_slide_title": "Let's go",
    "outro_slide_you_are_prepared": "Thanks for your patience! Now you are prepared to <span class=\"action-text\"></span>.",
    "outro_slide_keyguard": "For that purpose, in the next step a popup window will open which contains the Keyguard app. Just follow the steps there and see you very soon in Nimiq Safe!",
    "outro_slide_keyguard_button": "Open Keyguard",
    "outro_slide_ledger_button": "Import from Ledger",
};
export function getString(id) {
    //return "TRANSLATABLE";
    if (!STRINGS[id]) throw new Error("no " + id);
    return STRINGS[id] ? STRINGS[id] : "(missing translation: " + id + ")";
}
